package com.aws.aws_dropbox_um.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "userData")
public class User implements Serializable {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;
    @DynamoDBAttribute
    private String userNm;
    @DynamoDBAttribute
    private String desc;
    @DynamoDBAttribute
    private String createdDt;
    @DynamoDBAttribute
    private String modifiedDt;
    @DynamoDBAttribute
    private String fileNm;
}
